name: flask-restx
channels:
  - conda-forge
  - defaults
dependencies:
  - python<=3.6.13 # versão do heroku
  - flask
  - flask-restx
  - werkzeug<=1.0.0 # não funciona com versões maiores que 1.0.0
  - pip
  # instalando algo pelo pip
  # - pip:
    # - nomeDoPacote
    # - https://github.com/repositorio/archive/refs/heads/master.zip
    